export const SET_FIRST_LOADING_TRUE = 'SET_FIRST_LOADING_TRUE'
export const SET_FIRST_LOADING_FALSE = 'SET_FIRST_LOADING_FALSE'
export const SET_BTN_UPDATE_REALTY_CLICKED_TRUE = 'SET_BTN_UPDATE_REALTY_CLICKED_TRUE'
export const SET_BTN_UPDATE_REALTY_CLICKED_FALSE = 'SET_BTN_UPDATE_REALTY_CLICKED_FALSE'
export const SET_ALERT_VISIBILITY_TRUE = 'SET_ALERT_VISIBILITY_TRUE'
export const SET_ALERT_VISIBILITY_FALSE = 'SET_ALERT_VISIBILITY_FALSE'

export const GET_REALTIES = 'GET_REALTIES'
export const REALTY_SHOW = 'REALTY_SHOW'
export const REALTY_EDIT = 'REALTY_EDIT'
export const REALTY_UPDATE = 'REALTY_UPDATE'

export const GET_FEEDBACKS = 'GET_FEEDBACKS'
export const GET_IMAGES = 'GET_IMAGES'
export const GET_LANGUAGES = 'GET_LANGUAGES'



