export const SET_FIRST_LOADING_TRUE = 'SET_FIRST_LOADING_TRUE'
export const SET_FIRST_LOADING_FALSE = 'SET_FIRST_LOADING_FALSE'

export const SET_JUST_CREATED_RESOURCE_TRUE = 'SET_JUST_CREATED_RESOURCE_TRUE'
export const SET_JUST_CREATED_RESOURCE_FALSE = 'SET_JUST_CREATED_RESOURCE_FALSE'
export const SET_JUST_UPDATED_RESOURCE_TRUE = 'SET_JUST_UPDATED_RESOURCE_TRUE'
export const SET_JUST_UPDATED_RESOURCE_FALSE = 'SET_JUST_UPDATED_RESOURCE_FALSE'
export const SET_JUST_DELETED_RESOURCE_TRUE = 'SET_JUST_DELETED_RESOURCE_TRUE'
export const SET_JUST_DELETED_RESOURCE_FALSE = 'SET_JUST_DELETED_RESOURCE_FALSE'

export const SET_ALERT_CREATE_VISIBILITY_TRUE = 'SET_ALERT_CREATE_VISIBILITY_TRUE'
export const SET_ALERT_CREATE_VISIBILITY_FALSE = 'SET_ALERT_CREATE_VISIBILITY_FALSE'
export const SET_ALERT_UPDATE_VISIBILITY_TRUE = 'SET_ALERT_UPDATE_VISIBILITY_TRUE'
export const SET_ALERT_UPDATE_VISIBILITY_FALSE = 'SET_ALERT_UPDATE_VISIBILITY_FALSE'
export const SET_ALERT_DELETE_VISIBILITY_TRUE = 'SET_ALERT_DELETE_VISIBILITY_TRUE'
export const SET_ALERT_DELETE_VISIBILITY_FALSE = 'SET_ALERT_DELETE_VISIBILITY_FALSE'

export const GET_REALTIES = 'GET_REALTIES'
export const REALTY_CREATE = 'REALTY_CREATE'
export const REALTY_SHOW = 'REALTY_SHOW'
export const REALTY_EDIT = 'REALTY_EDIT'
export const REALTY_DELETE = 'REALTY_DELETE'

export const GET_FEEDBACKS = 'GET_FEEDBACKS'
export const FEEDBACK_CREATE = 'FEEDBACK_CREATE'
export const FEEDBACK_SHOW = 'FEEDBACK_SHOW'
export const FEEDBACK_EDIT = 'FEEDBACK_EDIT'
export const FEEDBACK_DELETE = 'FEEDBACK_DELETE'

export const GET_IMAGES = 'GET_IMAGES'
export const CREATE_FORM_DATA_IMAGES = 'CREATE_FORM_DATA_IMAGES'
export const CLEAN_FORM_DATA_IMAGES = 'CLEAN_FORM_DATA_IMAGES'

export const GET_LANGUAGES = 'GET_LANGUAGES'



